spring.application.name=workforce
spring.jpa.open-in-view=false
server.port =9076
logging.file.name=workforce.log
spring.datasource.url=jdbc:mysql://localhost:5432/workforce
spring.datasource.username=mysql
spring.datasource.password=Abhi@123
 #automatically performs the ddl operations
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

spring.mail.username=storm.962003@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.password=rysacufjkcckqzbr


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
spring.mail.properties.mail.smtp.quitwait=false



